### ISSUE TITLE
image preprocessing does not include normalization

### ISSUE THREAD

**Issue by njw0709** [ssundaram21/dreamsim#13]
Hello,

I am trying to adapt dreamsim for my work.
I realized that in your code, the preprocess function does not include image normalization (lines 230~235 in model.py).
If I want to use my own preprocessing function, should I also not normalize the image as the final stage?

Thanks!

**Comment by ssundaram21** [comment]
Hi - the images do get normalized, just not in that preprocess function in lines 230-235. Normalization happens inside the PerceptualModel class (defined [here](https://github.com/ssundaram21/dreamsim/blob/99222ad4cd4512e975721665336fa8c795990ec3/dreamsim/model.py#L120) and applied [here]( https://github.com/ssundaram21/dreamsim/blob/99222ad4cd4512e975721665336fa8c795990ec3/dreamsim/model.py#L105)). This is done because the model may be an ensemble of backbones, so the image gets re-normalized before each pass according to whatever normalization that backbone requires.

Hope this clears it up, let us know if you have other questions!
